1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

3. Create a null vector of size 10 

In [2]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

6. Create a null vector of size 10 but the fifth value which is 1 

In [3]:
zero = np. zeros(10)
zero

zero[4] = 1
print(zero)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [4]:
A = np. arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [5]:
A = np. arange(50)
A = A[::-1]
A

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

 10. Find indices of non-zero elements from [1,2,0,0,4,0]

11. Create a 3x3 identity matrix

In [6]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [7]:
Z = np.random.rand(3, 3, 3)
Z

array([[[0.3860134 , 0.61282562, 0.06003236],
        [0.89076703, 0.54718785, 0.54759765],
        [0.56857945, 0.36481175, 0.86747042]],

       [[0.39320575, 0.51534729, 0.50377107],
        [0.53860862, 0.23296935, 0.36500173],
        [0.70744951, 0.87418834, 0.89145568]],

       [[0.75347624, 0.75875741, 0.46636328],
        [0.47669001, 0.93736362, 0.66822345],
        [0.86668083, 0.42366073, 0.31314739]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
A = np. random.rand(10, 10)
Amin, Amax = A.min(), A.max()
Amin, Amax 

(0.003640667726018121, 0.9954637743446235)

14. Create a random vector of size 30 and find the mean value

In [9]:
A = np.random.rand(30)
Mean = A.mean()
Mean

0.40912679601735763

 15. Create a 2d array with 1 on the border and 0 inside 

In [10]:
A = np.ones((5,5))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16.How to add a border (filled with 0's) around an existing array? 

In [11]:
A = np.ones((5,5))
A[:,[0,-1]] = 0
A[[0,-1], :] = 0
print(A)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression? 
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

19. Create a 8x8 matrix and fill it with a checkerboard pattern